apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-calculation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi
  template:
    metadata:
      labels:
        app: pi
    spec:
      containers:
      - name: pi-calculation
        image: yourusername/my-golang-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pi-service
spec:
  selector:
    app: pi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

