apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: progrium/stress
        command: ["stress"]
        args: ["--io", "2", "--hdd", "2"]
      nodeSelector:
        trace-target: "true"
